# Generated by Django 3.2.23 on 2023-12-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviedata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
