# Generated by Django 3.2.23 on 2024-01-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postted_by',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
